default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 110572

development:
  adapter: postgresql
  encoding: unicode
  database: universidade
  pool: 5
  username: postgres
  password: 123456
  host: localhost